name: asg017/setup-sqlite-dist
description: Setup and install sqlite-dist to a GitHub Actions workflow
author: Alex Garcia

branding:
  icon: package
  color: blue

inputs:
outputs:

runs:
  using: node24
  main: dist/index.js
